D:\DOS\D\PROJECTS\monocide\tools\salvador cga_font.rom cga_font.zx0
D:\DOS\D\PROJECTS\monocide\tools\salvador shadcube.raw shadcube.zx0
D:\DOS\D\PROJECTS\monocide\tools\salvador colorf1.raw colorf1.zx0
D:\DOS\D\PROJECTS\monocide\tools\salvador indiantp.raw indiantp.zx0
D:\DOS\D\PROJECTS\monocide\tools\salvador boxes.bin boxes.zx0
D:\DOS\D\PROJECTS\monocide\tools\salvador whichcga.bin whichcga.zx0

binobj cga_font.zx0 cga_font.obj zx0_cga_font
binobj shadcube.zx0 shadcube.obj zx0_shadcube
binobj colorf1.zx0 colorf1.obj zx0_colorf1
binobj indiantp.zx0 indiantp.obj zx0_indiantp
binobj boxes.zx0 boxes.obj zx0_boxes
binobj whichcga.zx0 whichcga.obj zx0_whichcga

dir cga_font.*
dir shadcube.*
pause
dir colorf1.*
dir indiantp.*
pause
dir boxes.*
dir whichcga.*
pause


